plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
enableInlineBuilds: true
# disable pnp to ease transition from lerna
# TODO: fix pnp related issues and remove the following line
nodeLinker: node-modules
# several build tools fails to run properly with hosting
# e.g. sass in @fullweb/website can't find @material/drawer
nmHoistingLimits: workspaces
