module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "scope-enum": [
      2,
      "always",
      [
        "docs",
        "code-samples",
        "codelabs",
        "data-driven-pwa",
        "illustrations",
        "eni-dpawm",
        "perf",
        "helpers",
        "helpers-lazy-router",
        "helpers-el",
        "helpers-template",
        "benchmark",
        "daucus",
        "daucus-cli",
        "daucus-pandoc",
        "panpress",
        "panpress-cli",
        "panpress-starter",
        "panpress-webapp",
        "slides",
        "slides-wof-1",
        "slides-wof-2",
        "slides-vanilla-1",
      ],
    ],
    "subject-case": [1, "always", "lowerCase"],
  },
};
