sequenceDiagram
  participant U as Utilisateur
  participant N as Navigateur
  participant S as Serveur HTTP
  participant A as API

  U->>N: www.mon-blog.com
  N->>S: GET /
  S->>S: route * "index.html"
  S-->>N: index.html
  activate N
    Note left of N: Analyse de l'HTML
    N->>N: &lt;script src="app.js"&gt;
    N->>S: GET app.js
    S-->>N: app.js
    N-->>U: rendu de l'accueil
  deactivate N
  U->>N: click "article 1"
  activate N
    Note left of N: Rendu dynamique
    N->>N: fetch(API/posts/1)
    N->>A: GET /posts/1
    A-->>N: JSON
    N->>N: JSON->HTML
    N-->>U: rendu de "article 1"
  deactivate N
