/* eslint-disable max-classes-per-file */
import { AbstractRouter } from "@modern-helpers/router";
import { routeFinder } from "./route-finder.js";

/**
 * @typedef {import('@daucus/core').SimpleRoutesConfig} SimpleRoutesConfig
 * @typedef {import('@daucus/core').Route} Route
 * @typedef {import("@modern-helpers/router/src/navigation").NavigationOptions} NavigationOptions
 * @typedef {[string, NavigationOptions | undefined]} Navigation
 * @typedef {import('./find-route').PositiveRouteMatch} PositiveRouteMatch
 */

export class ProjectChangeEvent extends CustomEvent {
  /**
   * @param {string} projectName
   */
  constructor(projectName) {
    super("project-change", {
      detail: { projectName },
    });
  }
}

export class RouteMatchEvent extends CustomEvent {
  /**
   * @param {PositiveRouteMatch} routeMatch
   * @param {string} base base href
   * @param {URLSearchParams | null} [params] get parameters
   * @param {string} [hash] fragment identifier (without '#')
   */
  constructor(routeMatch, base, params, hash) {
    super("route-match", {
      detail: {
        projectName: routeMatch.projectName,
        route: routeMatch.route,
        templateHRef: `${base + routeMatch.projectName}/${
          routeMatch.route.templateUrl
        }`,
        hash,
        params,
      },
    });
  }
}

/**
 * Programmatic Router for Daucus
 *
 */
export class DaucusRouter extends AbstractRouter {
  /**
   * @param {SimpleRoutesConfig} routes autogenerated routes (`import("./_daucus_/routes.js")`)
   * @param {string} defaultPath path of the route to use when navigation failed
   * @param {string} baseDir base href (i.e. the URL prefix added to all route paths)
   */
  constructor(routes, defaultPath, baseDir) {
    super();
    /** @private */
    this._findDaucusRoute = routeFinder(routes).bind(this);
    /** @private */
    const defaultDaucusRouteMatch = this._findDaucusRoute(defaultPath);

    if (!defaultDaucusRouteMatch) {
      throw new Error(`can't find any route for default path ${defaultPath}`);
    }

    /** @private */
    this._defaultPath = defaultPath;
    /** @private */
    this._defaultDaucusRouteMatch = defaultDaucusRouteMatch;
    /** @private */
    this._baseDir = baseDir;
    /** @private */
    this._currentProject = "";
  }

  /**
   * Name of the current Daucus project
   */
  get currentProject() {
    return this._currentProject;
  }

  /**
   * @internal
   * @param {string | null} path
   * @param {import("@modern-helpers/router").NavigationOptions} [options]
   * @param {URLSearchParams} [params]
   * @param {string} [hash]
   */
  async renderOrRedirect(path, options, params, hash) {
    const routeMatch =
      path === this._defaultPath
        ? this._defaultDaucusRouteMatch
        : this._findDaucusRoute(path);
    if (!routeMatch.route) {
      /** @type {Navigation} */
      const redirection = [this._defaultPath, options];
      return redirection;
    }
    if (routeMatch.projectName !== this._currentProject) {
      this._currentProject = routeMatch.projectName;
      this.dispatchEvent(new ProjectChangeEvent(this._currentProject));
    }
    this.dispatchEvent(
      new RouteMatchEvent(
        // @ts-ignore routeMatch.route is truthy
        routeMatch,
        (this.base || "/") + this._baseDir,
        params,
        hash
      )
    );
    return null;
  }
}
